### ISSUE TITLE
[meta] Data browser

### ISSUE THREAD

**Issue by schickling** [graphcool/console#194]
Related:

- [ ] Clicking on the first row item in the "Add Field Column" creates a new item #269
- [x] ID should always be the first column in databrowser #272
- [x] "Import JSON" button is slightly smaller than the other buttons #271
- [x] Databrowser => some redux issue? #270

**Comment by brene** [comment]
- [ ] add row misaligns with rest of the data browser
- [ ] wiki for data browser

**Comment by timsuchanek** [comment]
- [ ] DateTime timezone offest bug
- [ ] Fix NewNode tabbing behavior
- [ ] Fix NewNode standard edit, but only scalar types
- [ ] Fix NewNode empty Model

**Comment by sorenbs** [comment]
This looks so sweet!

Arrow down when relation list is open should cycle the relation list instead of moving cursor to row below. Pressing enter should select relation item without saving row and close relation list. Pressing escape should close relation list and allow normal arrow navigation.

![image](https://cloud.githubusercontent.com/assets/281337/19272731/ebaa407e-8fc9-11e6-9446-53e88930d07b.png)

**Comment by timsuchanek** [comment]
@sorenbs Good point, done and pushed to dev :)
