### ISSUE TITLE
[meta] Permissions

### ISSUE THREAD

**Issue by schickling** [graphcool/console#244]
- [x] Can't remove role from Authenticated permission #242
- [x] Permission level "Related" not selectable #241 
- [x] Permission hierarchy #239
- [x] CSS misalignment in permissions editing #238
- [x] Reset permissions for whole model #83
