### ISSUE TITLE
[meta] Redesign/Restructure

### ISSUE THREAD

**Issue by schickling** [graphcool/console#263]
- [ ] Accounts Page header bug https://github.com/graphcool/dashboard/issues/254
- [ ] Wrong pluralization in number of items https://github.com/graphcool/dashboard/issues/262
- [ ] Arrow in API Endpoint not clickable https://github.com/graphcool/dashboard/issues/259
