### ISSUE TITLE
[meta] New field popup

### ISSUE THREAD

**Issue by schickling** [graphcool/console#339]
- [x] Field popup: enabling default value for Enum without changing dropdown sets it to empty string #223
- [x] Changing from list to scalar results in "migration value" error, but there's no migration option #305
- [x] Field popup: Migration value info is wrong #218
- [x] Entering Field Names UX #212

**Comment by timsuchanek** [comment]
all issues resolved
