### ISSUE TITLE
[meta] onboarding refinement

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#399]
- [x] Onboarding wording: Create a model called "Post" #395
 - [x] Onboarding for Relations: Better UX if Field already exists #388
 - [x] Onboarding: Playground popup: Wasn't obvious to click #396
 - [x] Onboarding: GraphiQL introduction is overwhelming #364
 - [x] Onboarding - get in again when focus lost #402 
 - [x] Onboarding graphiql: show task when popup closed #403
