### ISSUE TITLE
Todo Functions [meta]

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#902]
- [ ] Delete doesn't work
- [x] Webhook not fetched when re-editing
- [ ] force name when creating
