### ISSUE TITLE
Functions [meta]

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#954]
## Todo Console in general
- [ ] update notice

## Todo Popup

- [x] next level examples (with annotations)
- [x] docs don't work properly in fullscreen mode
- [x] better responsiveness fullscreen mode
- [x] less text on RP define functions screen
- [x] hide webhookurl for inlinecode again
- [x] fix rp example event again
- [x] test output 13/14px
- [x] make test logs beautiful
- [x] add shortcut cmd+enter to test function
- [x] fix logs scrolling + order
- [x] do not close fullscreen mode on esc (annoying while editing and closing auto completion)
- [x] resetting width when fullscreen is toggled
- [x] make editing available through url
- [x] fix example event for RP
- [x] Fix updating sss #973 
- [x] Fix links in functions view question mark #966
- [x] more sophisticated example generation
- [x] check always lowercase headers #948 
- [x] Rename "Set Event Type" -> "Choose Event Trigger"
- [x] code editor: fill complete space
- [x] Choose Trigger => Configure Trigger
- [x] Graphcool Checks
- [x] hover on in between states - explain what happens
- [x] add examples to steps
- [x] do not lose focus on tab #971 
- [x] When updating: make sure it's not `UserInput`
- [x] webhook editing - add ability to edit headers inline
- [x] fix toggling between webhook/inline code
- [x] fix header update
- [x] autoFocus to first input after adding header
- [x] wording Step 0

## Todo Backend
- [ ] better input type
- [ ] migrate functions

## Todo IDE Mode
- [x] Fullscreen IDE Mode

## Optional (fun)
- [ ] backticks don't work in functions syntax highlighting

## Done
- [x] clear button moves
- [x] add test button for fullscreen
- [x] force adding function name
- [x] function list: invalid date -> more beautiful (no recent calls)
- [x] rm beta flag
