### ISSUE TITLE
Onboarding [meta]

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/console#955]
- [x] continue from any point in onboarding bar
- [x] add arrow to onboarding bar
- [x] add skip to onboarding bar
